### ISSUE TITLE
POST images to resize, etc.

### ISSUE THREAD

**Issue by saschwarz** [agschwender/pilbox#68]
For my project I'd like to form POST images to pilbox and resize them. Was wondering if you already had an example of that or would be interested in a PR if I added that functionality? I'm thinking all pilbox options would be made available via the POST(?).
  
My use case is a mobile app where people will import (possibly) large images for which the app only needs much lower quality/smaller images. Once converted they'd be stored locally. It's not really the proxy use case pilbox targets, but thought you might be interested.

**Comment by agschwender** [comment]
I'd never really considered implementing a `post` since the primary objective was to provide a drop-in replacement for an image URL in an `img` tag. That being said, I'd opt for extending pilbox to support a`post` endpoint: https://github.com/agschwender/pilbox#extension. You should be able to implement it such that it can accept the file data and call `render_image` with the file data to do the resize. You may need to call the internals of `render_image` yourself if you can't simultaneously stream the output to the client and store it.
